name: CI

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'An optional comment'
        required: false

jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Execute test case
        run: |
          xvfb-run -a pytest -s tests/test_musala.py
